### ISSUE TITLE
播放页面没下载选项

### ISSUE THREAD

**Issue by wmcam** [Xmader/bilitwin#1]
### 哪一个页面？
https://www.bilibili.com/video/av32616834/

### 出了什么问题？
播放页面无任何下载按钮

### 用的浏览器是？
谷歌浏览器
版本 69.0.3497.100（正式版本）

**Comment by xuejianxianzun** [comment]
同上~
以前用过这个脚本，今天安装上发现没有下载按钮了，期待修复，谢谢~

**Comment by Xmader** [comment]
右键一下播放器就可以了😉
