### ISSUE TITLE
没有AAC音频下载功能

### ISSUE THREAD

**Issue by ShiLei96** [Xmader/bilitwin#102]
### 哪一个页面？
播放页面

### 出了什么问题？
没有/找不到 音频下载

### 用的浏览器是？
Chrome 版本 88.0.4324.182（正式版本） （64 位）

**Comment by Xmader** [comment]
AAC音频下载要在 `缓存全部+自动合并` 后才会出现

![](https://user-images.githubusercontent.com/16057139/108649851-29c5bb80-748c-11eb-86ed-e93cd0a96a7c.png)
