### ISSUE TITLE
如何单独打开设置页面?

### ISSUE THREAD

**Issue by molehzy** [Xmader/bilitwin#18]
### 哪一个页面？
所有播放页面

### 出了什么问题？
我在设置里把标题旁的下载链接去掉后在播放器内右键无效

### 用的浏览器是？
360安全浏览器10.0.1581.0基于Chrome内核63.0.3239.132

**Comment by Xmader** [comment]
如果播放器内右键无效，设置页面暂时是没有办法单独打开的

可以尝试重置脚本的设置
按 <kbd>F12</kbd> 打开浏览器控制台，选择 Console（控制台）标签页，在下方的空白处输入下列脚本按回车键即可
```js
localStorage.removeItem("BiliTwin"),location.reload()
```
