### ISSUE TITLE
「Feature Request」One-Click Download Multiple Video

### ISSUE THREAD

**Issue by SJTUboy** [Xmader/bilitwin#23]
### 哪一个页面？
https://www.bilibili.com/video/av23036078

### 出了什么问题？
As you can see. There are 20P in this video. I was wondering if there are any way to one-click download them ( I mean: to 20 videos not one video)

Traditional way is download 20 videos seperately. ( at least 20*3 click)

![image](https://user-images.githubusercontent.com/13373715/53245451-ad574100-36e8-11e9-971c-3528c16172d6.png)

### 用的浏览器是？
Nothing to do with browser version

**Comment by Xmader** [comment]
BiliTwin already has the feature you required. You can use it like this.

1. Right click on the video to open the context menu. 
2. Click `批量下载` (It means Batch Download.)
![](https://user-images.githubusercontent.com/16057139/53270976-1a53e200-36bb-11e9-8406-8c896ae0d292.png)
3. Wait a moment
4. Then click `一键开始缓存+批量合并`
![image](https://user-images.githubusercontent.com/16057139/53272159-7ec47080-36be-11e9-91fe-aea9798ed7f2.png)

You can download all the videos in 3 clicks.
