### ISSUE TITLE
合并功能无法使用

### ISSUE THREAD

**Issue by He1lscythe** [Xmader/bilitwin#28]
### 哪一个页面？视频下载页面
![image](https://user-images.githubusercontent.com/46492541/55944384-1421c100-5c7b-11e9-93df-086244278791.png)

### 用的浏览器是？chrome
![捕获](https://user-images.githubusercontent.com/46492541/55944492-4cc19a80-5c7b-11e9-9e7e-07eaa4e18321.PNG)

**Comment by He1lscythe** [comment]
我现在在firefox 上也遇到了相同的问题

**Comment by ly5902534** [comment]
感觉是必须点上面的下载合并到一起
