### ISSUE TITLE
批量下载时候建议自动给视频增加序号！！

### ISSUE THREAD

**Issue by qq1792** [Xmader/bilitwin#29]
### 哪一个页面？
批量下载功能

### 出了什么问题？
较多视频批量下载后，排序混乱，建议按原来视频ID，自动给视频增加序号，方便观看。

### 用的浏览器是？
chrome

**Comment by Xmader** [comment]
您好，在最新的 `v1.22.2` 版本中已经增加了这个功能，请尽请享用吧。
