### ISSUE TITLE
作者您好，从昨天开始插件失效了。

### ISSUE THREAD

**Issue by rayagony** [Xmader/bilitwin#3]
### 哪一个页面？
biibili视频播放页面

### 出了什么问题？
点击播放后也没有出现下载选项，右键屏幕没有出现插件的选项菜单

### 用的浏览器是？
Chrome  版本 69.0.3497.100（正式版本） （64 位）

**Comment by Xmader** [comment]
您好，
我这边用Chrome测试是没有问题的，
请确保使用的是最新的v1.16.1版本的脚本喔，旧版本可能会有一些小问题。

如果可以，请按F12或Ctrl+Shift+I打开开发者工具，选择Console(控制台)，看一看有没有红色的报错信息。如果有，请截图一 一发给我。

**Comment by rayagony** [comment]
插件失效原因与其他插件产生了冲突，现在已经解决。

**Comment by Xmader** [comment]
没问题就好🙂
