### ISSUE TITLE
不支持新版播放器了啊

### ISSUE THREAD

**Issue by y4kumo** [Xmader/bilitwin#33]

**Comment by y4kumo** [comment]
好像又可以了。。虽然关闭了其他的所有脚本。但昨天就是死活出不来右键的monkey  polyfill菜单。

**Comment by Xmader** [comment]
昨天是敏感日子，你不知道吗？
B站限制了许多功能

**Comment by y4kumo** [comment]
另外还有一个问题是    打开了polyfill 功能增强总开关    换p之后    自定义的播放速度还是不能被记住啊。又回到了默认的一倍速。(没有其他脚本影响   只运行了这一个脚本。)

**Comment by y4kumo** [comment]
自定义播放速度   放着放着恢复默认速度了。。  再重新定义也没用    刷新网页也没用。。

**Comment by Xmader** [comment]
您好，在 `v1.23.8` 版本中已经修复
