### ISSUE TITLE
bilibili旧版播放器没效果

### ISSUE THREAD

**Issue by MaxMadcc** [Xmader/bilitwin#34]
### 哪一个页面？
bilibili旧版播放器

### 出了什么问题？
对播放器按右键不显示那两个菜单了
如图
![bilibili_1](https://user-images.githubusercontent.com/19978097/59019792-4155ae80-887b-11e9-8294-a0669b8fa879.png)
![bilibili_2](https://user-images.githubusercontent.com/19978097/59019793-4155ae80-887b-11e9-87a1-fb6bdee0feb8.png)
![bilibili_3](https://user-images.githubusercontent.com/19978097/59019795-41ee4500-887b-11e9-880f-7d807adce274.png)

### 用的浏览器是？
Firefox 67.0.1和Chrome 74.0.3729.169

**Comment by Xmader** [comment]
您好，最新的 `v1.22.3` 版本已经修复了这个问题
