### ISSUE TITLE
Aria2 PRC地址无法识别

### ISSUE THREAD

**Issue by der035** [Xmader/bilitwin#5]
### 哪一个页面？
Aria2 PRC地址输入

### 出了什么问题？
输入Aria2路由器端带Token的地址
提示Aria2 connection failed. Please provide a valid server 

### 用的浏览器是？
Safari

**Comment by Xmader** [comment]
您好，
最新版脚本已经修复了输入带Token的地址无法识别的问题，
但是由于浏览器默认阻止在一个https页面中发送http请求，
如果你的aria2没有开启 https 支持，可能还是用不了。
