### ISSUE TITLE
不显示下载 无任何显示

### ISSUE THREAD

**Issue by BrokenChip** [Xmader/bilitwin#50]
### 哪一个页面？
https://www.bilibili.com/video/av11233336?from=search&seid=15072024368619635751

### 出了什么问题？
安装后刷新刷新原界面 把视频整个放一边 更换播放方式 都没能刷出来那个下载有关的对象（听说是在标题底下吧）

### 用的浏览器是？
Firefox 68.0.2 (64 位)

万望殿下查明原因

**Comment by Xmader** [comment]
您好，
下载按钮在右键菜单里也有的呢，
有时需要点击右键才会在标题下显示
