### ISSUE TITLE
可以加入在自动生成ASS弹幕前设置分辨率(PlayResX和PlayResY)的功能？

### ISSUE THREAD

**Issue by jhkhjgfjjjkj** [Xmader/bilitwin#6]
原分辨率太小的话，导入播放器后会有字体过大的情况

**Comment by Xmader** [comment]
这个是获取原始视频分辨率的bug，我尽量在下一个版本修复。

**Comment by jhkhjgfjjjkj** [comment]
> 這個是獲取原始視頻分辨率的錯誤，正常情況下會匹配視頻分辨率生成屁股文件，
> 我盡量在下一個版本修復。



> 這個是獲取原始視頻分辨率的bug，正常情況下會匹配視頻分辨率生成ass文件，
> 我盡量在下一個版本修複。

希望可以自定义

**Comment by Xmader** [comment]
好的，
我已在 v1.17.0 版本中加入了这个功能，可以在设置中开启。
