### ISSUE TITLE
标题下的俩个按钮咋删去？

### ISSUE THREAD

**Issue by Super-cute-new** [Xmader/bilitwin#61]
### 哪一个页面？
播放页面
标题下的俩个按键

### 出了什么问题？
标题下的俩个按钮咋删去？
因为这个会和宽屏下移
所以想把这个去掉

### 用的浏览器是？

谷歌

**Comment by Xmader** [comment]
您好，这个是可以在设置里去掉的喔
右键视频，BiliPloyfill，进入到设置，取消勾选 `在视频标题旁添加链接` (倒数第七个)，保存刷新就可以了
