### ISSUE TITLE
找不到下载的视频的位置

### ISSUE THREAD

**Issue by wlg2003** [Xmader/bilitwin#63]
### 哪一个页面？
声之形
### 出了什么问题？
找不到下载的位置

### 用的浏览器是？
微软新出的edge浏览器

**Comment by Xmader** [comment]
您好，
这个是关于 Edge 浏览器的 ES6 特性兼容问题，
很快就会修复

**Comment by Xmader** [comment]
您好，
这个问题已在最新的 `v1.23.10` 版本中修复
（请使用 [国产浏览器 和 Edge浏览器 兼容版本](https://www.xmader.com/bilitwin/biliTwinBabelCompiled.user.js)）

下载按钮在视频右键菜单中，或者在视频的标题栏下方可以找到
![](https://user-images.githubusercontent.com/16057139/69844277-7c88d700-1239-11ea-836a-12e6415afdea.png)
