### ISSUE TITLE
批量下载无法生效

### ISSUE THREAD

**Issue by beahyuk** [Xmader/bilitwin#67]
### 哪一个页面？

批量下载
### 出了什么问题？
右键-批量下载 没有反应
以前是爬虫那样，p =1，2这样抓取，但是今天用没有反应
我11.26号还可以批量下载，今天没反应了，然后我更新到最新版，1.23.10 也没有反应

### 用的浏览器是？
谷歌chrome

**Comment by ArchanJin** [comment]
同样的问题，浏览器是Firefox

**Comment by Xmader** [comment]
您好，这个问题已经在 `v1.23.11` 版本中修复
