### ISSUE TITLE
题外话，还是我，请问B站弹幕xml怎么批量转ass呀

### ISSUE THREAD

**Issue by GarboSun** [Xmader/bilitwin#86]
考古看《铁齿铜牙纪晓岚》，B站下架了，找到了视频资源，找到了网友分享了xml格式的弹幕，想用MKVToolNix合并，但是xml不被支持。

我猜如果原始弹幕是xml格式，大神给出的是ass字幕，那么应该是知道怎么转换的。

求支招，尽量傻瓜式。

**Comment by Xmader** [comment]
<https://tiansh.github.io/ass-danmaku-online/>

**Comment by GarboSun** [comment]
太感谢了！要的就是这个！
