### ISSUE TITLE
大佬好像新版本的chrome不兼容脚本了...

### ISSUE THREAD

**Issue by Cmoe306** [Xmader/bilitwin#87]
### 出了什么问题？

昨天还可以正常下载，今天打开B站视频页面会再次刷新，左上角的子选单也不见了...
### 用的浏览器是？
chrome浏览器最新版本

**Comment by miohsu** [comment]
我也遇到了同样的问题。
视频：https://www.bilibili.com/video/BV1Hy4y1C7Md?t=4
浏览器版本：Chrome 版本 86.0.4240.111（正式版本） （64 位）

**Comment by Xmader** [comment]
`v1.23.16` 中已经修复了
