### ISSUE TITLE
视频播放页面加载不全

### ISSUE THREAD

**Issue by HashLiver** [Xmader/bilitwin#9]
### 哪一个页面？
任一普通的视频播放页（av*****）、新版播放器

### 出了什么问题？
脚本版本是v1.20.0
最近貌似更新了[无需右键播放器就能显示下载按钮](https://greasyfork.org/zh-CN/scripts/372516-bilibili-merged-flv-mp4-ass-enhance/diff?v1=642217&v2=642011)对吧。
然而当脚本优先播放器加载后，就会出现这样的问题：
![default](https://user-images.githubusercontent.com/42889797/47995164-66404280-e12f-11e8-8aab-ec9c258fc426.gif)
以前的版本都是等播放器加载完后才敢点击，不然也会出上图一样的问题。

旧版播放器无此问题，可能是我这台笔电配置比较渣吧:(

### 用的浏览器是？
Chrome 70.0.3538.77

**Comment by Xmader** [comment]
这个bug在 `v1.19.4 ` 版本中确实存在，但我已在 `v1.20.0` 版本中修复了，
可能是浏览器缓存的问题，重启浏览器再打开试试看？

**Comment by HashLiver** [comment]
@Xmader 感谢答复，重装就好了
