### ISSUE TITLE
最新版本的chrome和Edge都无法正常使用脚本...

### ISSUE THREAD

**Issue by Cmoe306** [Xmader/bilitwin#90]
### 哪一个页面？
https://www.bilibili.com/video/BV13D4y1X7w7?p=1
https://www.bilibili.com/video/BV1Xa4y1p7a8
https://www.bilibili.com/video/BV17V411a7N9
### 出了什么问题？
无法调用脚本进行下载...

### 用的浏览器是？
chrome 87.0.4280.66（正式版本） （64 位）
Edge 版本 87.0.664.41 (官方内部版本) (64 位)

**Comment by Xmader** [comment]
已经在 `v1.23.17` 版本中修复
