### ISSUE TITLE
字幕无法下载，显示【正在ASS】

### ISSUE THREAD

**Issue by GarboSun** [Xmader/bilitwin#99]
### 哪一个页面？
https://www.bilibili.com/video/BV1xA411p7eq?from=search&seid=8669427605824117227

### 出了什么问题？
字幕下载不了
https://tva1.sinaimg.cn/large/008eGmZEgy1gn03plmvkdj30tw06ut9h.jpg

### 用的浏览器是？
谷歌 版本 87.0.4280.141（正式版本） (x86_64)

**Comment by GarboSun** [comment]
【正在ASS】是什么意思呀，好多精华弹幕都下不了，sad。

**Comment by Xmader** [comment]
已修复
